import {StintType} from "../enums/stint-type.enum";
import {IEvent} from "../models/event.model";
import {Stint} from "../models/stint.model";
import {add} from "date-fns";

export class StrategyCalculator {
    /**
     * The strategy table generated by team AVG stats and Normal stints only.
     * Used for reference and to give a base table to users.
     * @protected
     */
    protected avgStrategyTable: Stint[] = [];
    /**
     * The strategy table modified by user input.
     * Using the avgStrategyTable as base.
     * @protected
     */
    protected userStrategyTable?: Stint[];

    constructor(
        public readonly event: IEvent
    ) {
        this.avgStrategyTable = this.generateAvgStrategyTable();
    }

    /**
     * Returns the strategy table, if the user has modified it, it will return the user modified table.
     */
    get strategyTable(): Stint[] {
        return this.userStrategyTable || this.avgStrategyTable;
    }

    /**
     * Generates the base strategy table using the team AVG stats and Normal stints only.
     * @returns The strategy table.
     */
    protected generateAvgStrategyTable(): Stint[] {
        const stints: Stint[] = []
        const targetLapCount = (this.event.duration * 60) / this.event.team.targetStintInfos[StintType.NORMAL].lapTimeWithPit;
        const targetStintCount = targetLapCount / this.event.team.targetStintInfos[StintType.NORMAL].lapCount;
        const targetStintCountRound = Math.round(targetStintCount);
        const lastStintLapCount = Math.round(
            this.event.team.avgDriver.stintsInfos[StintType.NORMAL].lapCount
            *
            targetStintCount - Math.floor(targetStintCount)
        );

        // Generate the full stints
        for (let i = 0; i < targetStintCountRound - 1; i++) {
            const s = new Stint(
                i + 1, StintType.NORMAL, this.event.team.targetStintInfos,
                add(new Date(this.event.raceStart),
                    {seconds: this.event.team.targetStintInfos[StintType.NORMAL].trackTimeWithPit * i}),
                this.event.team.avgDriver);
            stints.push(s);
        }
        // Generate the last stint
        stints.push(new Stint(
            targetStintCountRound,
            StintType.NORMAL,
            this.event.team.targetStintInfos,
            stints[stints.length - 1].endTime,
            this.event.team.avgDriver,
            lastStintLapCount
        ));

        return stints;
    }

}
